name: hugo blog

on:
  push:
    tags:
      - '*'
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    # permissions:
    #   contents: read
    #   packages: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.99.1'
          extended: true

      - name: build
        run: hugo --minify

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: ./public
#           # cname: wolanx.com # 重点 ！！！
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: BruceYuan1993/BruceYuan1993.github.io # remote branch
          publish_dir: "./docs"
#           cname: blog.funnycode.org.cn          
          keep_files: false # remove existing files
          publish_branch: docs  # deploying branch
          commit_message: ${{ github.event.head_commit.message }}
